export const API = {
  historias:            "/api/historias",
  historiasSync:        "/api/historias/sync",
  historia:             (id: string) => `/api/historias/${id}`,
  historial:            (id: string) => `/api/historias/${id}/historial`,
  casos:                "/api/casos",
  casosSync:            "/api/casos/sync",
  casosBatch:           "/api/casos/batch",
  caso:                 (id: string) => `/api/casos/${id}`,
  tareas:               "/api/tareas",
  tareasSync:           "/api/tareas/sync",
  tarea:                (id: string) => `/api/tareas/${id}`,
  config:               "/api/config",
  sprints:              "/api/sprints",
  sprint:               (id: string) => `/api/sprints/${id}`,
  notificaciones:       "/api/notificaciones",
  notificacionesMarcar: "/api/notificaciones/marcar-todas",
  notificacion:         (id: string) => `/api/notificaciones/${id}`,
  authLogin:            "/api/auth/login",
  authLogout:           "/api/auth/logout",
  authMe:               "/api/auth/me",
  authRefresh:          "/api/auth/refresh",
  authPassword:         "/api/auth/password",
  users:                "/api/users",
  user:                 (id: string) => `/api/users/${id}`,
  userAsignaciones:     (id: string) => `/api/users/${id}/asignaciones`,
  grupos:               "/api/grupos",
  grupo:                (id: string) => `/api/grupos/${id}`,
  grupoMetricas:        (id: string) => `/api/grupos/${id}/metricas`,
  audit:                "/api/audit",
  health:               "/api/health",
  exportCsv:            "/api/export",
  exportPdf:            "/api/export/pdf",
} as const
